port: 4009
baseurl: 'http://localhost'
secretkey: '7D6FF21AA328A48BC13AF2E285E6FE69'
middleurl: '/media_service'

# MariaDB dev
development:
    username: 'root'
    password: ''
    database: ''
    host: '127.0.0.1'
    dialect: 'mysql'

# MariaDB prod
production:
    username: ''
    password: ''
    database: ''
    host: '127.0.0.1'
    dialect: 'mysql'
    #logging: false

# MariaDB test
test:
    username: ''
    password: ''
    database: ''
    host: '127.0.0.1'
    dialect: 'postgres'

priveleges:
    create: 'ms.create'
    read: 'ms.read'
    update: 'ms.update'
    delete: 'ms.delete'